# Ejercicios de la librería Numpy

0. Importa la librería numpy como np

In [ ]:
import numpy as np


1. Crear un arreglo de 10 ceros

In [1]:
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2. Crear un arreglo de 10 unos

In [7]:
import numpy as np
arr=np.full(10,1)
print(np.ones(10))
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1]


3. Crear un arreglo de 10 cincos

In [8]:
import numpy as np
print(np.full(10,5))

[5 5 5 5 5 5 5 5 5 5]


4. Crear un arreglo con todos los numeros pares del 10 al 50

In [11]:
import numpy as np
print(np.arange(0,51,2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50]


5. Crear una matriz 3x3 con valores del 0 al 8

In [14]:
import numpy as np
arr=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(arr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


6. Crear una matriz de identidad de 3x3

In [15]:
import numpy as np
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


7. Utilizar numpy para geneara un numero aleatorio entre 0 y 1

In [24]:
import numpy as np
a=np.random.random(1)
print(a)

[0.25805356]


8. Utilizar numpy para generar un arreglo de 25 numeros aleatorioas con una distribucion normal

In [43]:
import numpy as np
arr=np.random.normal(25,1,25)
print(arr)

[24.43669684 25.22362091 25.29762619 23.63939064 24.25816958 24.67341038
 26.17924118 24.56172022 25.98997127 25.81875852 25.59189254 25.11613165
 25.34999958 25.10697279 26.69888687 24.34477084 25.58514182 25.36392965
 24.71463241 24.21883597 24.35283433 24.3682888  25.47881575 23.80850317
 25.04592944]


9. Crear la siguiente matriz

10. Crear un arreglo de 20 valores lineales entre 0 y 1

In [44]:
import numpy as np

arr=np.linspace(0,1)
print(arr)

[0.         0.02040816 0.04081633 0.06122449 0.08163265 0.10204082
 0.12244898 0.14285714 0.16326531 0.18367347 0.20408163 0.2244898
 0.24489796 0.26530612 0.28571429 0.30612245 0.32653061 0.34693878
 0.36734694 0.3877551  0.40816327 0.42857143 0.44897959 0.46938776
 0.48979592 0.51020408 0.53061224 0.55102041 0.57142857 0.59183673
 0.6122449  0.63265306 0.65306122 0.67346939 0.69387755 0.71428571
 0.73469388 0.75510204 0.7755102  0.79591837 0.81632653 0.83673469
 0.85714286 0.87755102 0.89795918 0.91836735 0.93877551 0.95918367
 0.97959184 1.        ]


### Seleccion e indices de Numpy
11. Se te daran varias matrices, se te pide replicar el resultado

In [45]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [66]:
import numpy as np
mat1=np.arange(12,16).reshape(1,4)
mat2=np.arange(17,21).reshape(1,4)
mat3=np.arange(22,26).reshape(1,4)
matRes=np.concatenate([mat1,mat2,mat])
print(matRes)





[[12 13 14 15]
 [17 18 19 20]
 [12 13 14 15]]


In [68]:
import numpy as np
mat1=np.arange(12,16).reshape(1,4)
mat2=np.arange(17,21).reshape(1,4)
mat3=np.arange(22,26).reshape(1,4)
matRes=np.concatenate([mat1,mat2,mat])

print(matRes[(matRes==20)])


[20]


In [92]:
import numpy as np

# crear matriz de 3 filas y 1 columna con los valores dados
matriz = np.array([[2], [7], [12]])

print(matriz)

[[ 2]
 [ 7]
 [12]]


In [97]:
import numpy as np
arr=np.arange(21,26).reshape(1,5)
print(arr)

[[21 22 23 24 25]]


In [99]:
import numpy as np
arr=np.arange(16,21).reshape(1,5)
arr2=np.arange(21,26).reshape(1,5)
arrR=np.concatenate([arr,arr2])
print(arrR)

[[16 17 18 19 20]
 [21 22 23 24 25]]


Luego continua con:
- Obten la suma de los valores de `mat`
- Obten la desviacion estandar de los valores de `mat`
- Obten la suma de las columnas de los valores de `mat`

In [108]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
sum=np.sum(mat)
print(sum)

desviacion=np.std(mat)
print(desviacion)

sumColum=np.sum(mat,axis=0)
print(sumColum)

325
7.211102550927978
[55 60 65 70 75]


# Ejercicios de la Librería Pandas

1. Escribir un programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla una serie con los datos de las ventas indexada por los años, antes y después de aplicarles un descuento del 10%.

In [7]:
import pandas as pd
import numpy as np
anioI=input("ingrese anio inicial")
anioF=input("Ingrese el año fin")

#creo dicts 
ventas={}
ventas2={}
for i in range(int(anioI),int(anioF)+1):
    ventas[i]=input("ingresa las ventas de este anio")
    ventas2[i]=int(ventas[i])*0.10+int(ventas[i])    
serieVentas=pd.Series(ventas)
serieVentas2=pd.Series(ventas2)
print("serie sin descuentos")
print(serieVentas)

print("serie Con descuentos")
print(serieVentas2)

serie sin descuentos

2012    10
2013    20
2014    30
dtype: object
serie Con descuentos
2012    11.0
2013    22.0
2014    33.0
dtype: float64


2. Escribir una función que reciba un diccionario con las notas de los alumno de un curso y devuelva una serie con la nota mínima, la máxima, media y la desviación típica.

In [23]:
import pandas as pd
notas={'Analisis':6,'Programacion':8,'Quimica':2}
def Notas(notas):
    #serie comun
    serieNota=pd.Series(notas)
    print(serieNota)
    
    #serie nota minima
    print("serie con la nota minaima")
    print(serieNota.min())
    #media
    print("serie con la media")
    print(serieNota.mean())
    
    #desviacion
    print("serie con la desviacion tipica")
    print(serieNota.std())
print(Notas(notas))

Analisis        6
Programacion    8
Quimica         2
dtype: int64
serie con la nota minaima
2
serie con la media
5.333333333333333
serie con la desviacion tipica
3.055050463303893
None


3. Escribir una función que reciba un diccionario con las notas de los alumnos de un curso y devuelva una serie con las notas de los alumnos aprobados ordenadas de mayor a menor.

4. Escribir programa que genere y muestre por pantalla un DataFrame con los datos de la tabla siguiente:

| Mes | Ventas | Gastos |
| --- | --- | --- |
| Enero | 30500 | 22000 |
| Febrero | 35600 | 23400 |
| Marzo | 28300 | 18100 |
| Abril | 33900 | 20700 |

5. Escribir una función que reciba un DataFrame con el formato del ejercicio anterior, una lista de meses, y devuelva el balance (ventas - gastos) total en los meses indicados.

6. El fichero cotizacion.csv contiene las cotizaciones de las empresas del IBEX35 con las siguientes columnas: nombre (nombre de la empresa), Final (precio de la acción al cierre de bolsa), Máximo (precio máximo de la acción durante la jornada), Mínimo (precio mínimo de la acción durante la jornada), volumen (Volumen al cierre de bolsa), Efectivo (capitalización al cierre en miles de euros). Construir una función que construya un DataFrame a partir del un fichero con el formato anterior y devuelva otro DataFrame con el mínimo, el máximo y la media de dada columna.

7. El fichero titanic.csv contiene información sobre los pasajeros del Titanic. Escribir un programa con los siguientes requisitos:

    1. Generar un DataFrame con los datos del fichero.
    2. Mostrar por pantalla las dimensiones del DataFrame, el número de datos que contiene, los nombres de sus columnas y filas, los tipos de datos de las columnas, las 10 primeras filas y las 10 últimas filas
    3. Mostrar por pantalla los datos del pasajero con identificador 148.
    4. Mostrar por pantalla las filas pares del DataFrame.
    5. Mostrar por pantalla los nombres de las personas que iban en primera clase ordenadas alfabéticamente.
    6. Mostrar por pantalla el porcentaje de personas que sobrevivieron y murieron.
    7. Mostrar por pantalla el porcentaje de personas que sobrevivieron en cada clase.
    8. Eliminar del DataFrame los pasajeros con edad desconocida.
    9. Mostrar por pantalla la edad media de las mujeres que viajaban en cada clase.
    10. Añadir una nueva columna booleana para ver si el pasajero era menor de edad o no.
    11. Mostrar por pantalla el porcentaje de menores y mayores de edad que sobrevivieron en cada clase.

8. Los ficheros emisiones-2016.csv, emisiones-2017.csv, emisiones-2018.csv y emisiones-2019.csv, contienen datos sobre las emisiones contaminates en la ciudad de Madrid en los años 2016, 2017, 2018 y 2019 respectivamente. Escribir un programa con los siguientes requisitos:

    1. Generar un DataFrame con los datos de los cuatro ficheros.
    2. Filtrar las columnas del DataFrame para quedarse con las columnas ESTACION, MAGNITUD, AÑO, MES y las correspondientes a los días D01, D02, etc.
    3. Reestructurar el DataFrame para que los valores de los contaminantes de las columnas de los días aparezcan en una única columna.
    4. Añadir una columna con la fecha a partir de la concatenación del año, el mes y el día (usar el módulo datetime).
    5. Eliminar las filas con fechas no válidas (utilizar la función isnat del módulo numpy) y ordenar el DataFrame por estaciones contaminantes y fecha.
    6. Mostrar por pantalla las estaciones y los contaminantes disponibles en el DataFrame.
    7. Crear una función que reciba una estación, un contaminante y un rango de fechas y devuelva una serie con las emisiones del contaminante dado en la estación y rango de fechas dado.
    8. Mostrar un resumen descriptivo (mínimo, máximo, media, etc.) para cada contaminante.
    9. Mostrar un resumen descriptivo para cada contaminante por distritos.
    10. Crear una función que reciba una estación y un contaminante y devuelva un resumen descriptivo de las emisiones del contaminante indicado en la estación indicada.
    11. Crear una función que devuelva las emisiones medias mensuales de un contaminante y un año dados para todos las estaciones.
    12. Crear un función que reciba una estación de medición y devuelva un DataFrame con las medias mensuales de los distintos tipos de contaminantes.

# Ejercicios de la librería Matplotlib

1. Escribir un programa que pregunte al usuario por las ventas de un rango de años y muestre por pantalla un diagrama de líneas con la evolución de las ventas.

2. Escribir una función que reciba una diccionario con las notas de las asignaturas de un curso y una cadena con el nombre de un color y devuelva un diagrama de barras de las notas en el color dado.

3. Escribir una función que reciba una serie de Pandas con las notas de los alumnos de un curso y devuelva un diagrama de cajas con las notas. El diagrama debe tener el título “Distribución de notas”.

4. Escribir una función que reciba una serie de Pandas con el número de ventas de un producto durante los meses de un trimestre y un título y cree un diagrama de sectores con las ventas en formato png con el titulo dado. El diagrama debe guardarse en un fichero con formato png y el título dado.

5. Escribir una función que reciba una serie de Pandas con el número de ventas de un producto por años y una cadena con el tipo de gráfico a generar (lineas, barras, sectores, areas) y devuelva un diagrama del tipo indicado con la evolución de las ventas por años y con el título “Evolución del número de ventas”.

6. Escribir una función que reciba un dataframe de Pandas con los ingresos y gastos de una empresa por meses y devuelva un diagrama de líneas con dos líneas, una para los ingresos y otra para los gastos. El diagrama debe tener una leyenda identificando la línea de los ingresos y la de los gastos, un título con el nombre “Evolución de ingresos y gastos” y el eje y debe empezar en 0.

7. El fichero bancos.csv contiene las cotizaciones de los principales bancos de España con : **Empresa** (nombre de la empresa), **Apertura** (precio de la acción a la apertura de bolsa), **Máximo** (precio máximo de la acción durante la jornada), **Mínimo** (precio mínimo de la acción durante la jornada), **Cierre** (precio de la acción al cierre de bolsa), **Volumen** (volumen al cierre de bolsa). Construir una función reciba el fichero bancos.csv y cree un diagrama de líneas con las series temporales de las cotizaciones de cierre de cada banco.

8. El fichero titanic.csv contiene información sobre los pasajeros del Titanic. Crear un dataframe con Pandas y a partir de él generar los siguientes diagramas.
    1. Diagrama de sectores con los fallecidos y supervivientes.
    2. Histograma con las edades.
    3. Diagrama de barras con el número de personas en cada clase.
    4. Diagrama de barras con el número de personas fallecidas y supervivientes en cada clase.
    5. Diagrama de barras con el número de personas fallecidas y supervivientes acumuladas en cada clase.